# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jeffa's Abend 
email: wuftymerguftyguff@gmail.com
description: > # this means to ignore newlines until "baseurl:"
     The so called life of Jeff Arthur YMMV
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: wuftmergufty
github_username:  wuftymerguftyguff

encoding: utf-8

# Build settings
markdown: kramdown

# Google services
google_analytics: UA-313584-16
